name: Pipeline Cypress E2E

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Pruebas E2E
        uses: cypress-io/github-action@v6
        with:
          start: node server.js
          wait-on: 'http://localhost:5000'